server:
  servlet:
    context-path: /api

auth:
  filter:
    exclusions: "/docs/index.html"

spring:
  profiles:
    active: test

  data:
    redis:
      url: redis://localhost:16379

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasd"
  access-expire-second: 1000000
  refresh-secret-key: "assfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasads"
  refresh-expire-second: 2000000

---
spring:
  config:
    activate:
      on-profile: local, dev, prd
  data:
    mongodb:
      uri: ${DB_URI}
    redis:
      url: ${REDIS_URL}

jwt:
  access-secret-key: ${JWT_ACCESS_SECRET_KEY}
  access-expire-second: ${JWT_ACCESS_EXPIRE_LENGTH}
  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
  refresh-expire-second: ${JWT_REFRESH_EXPIRE_LENGTH}


